chore(workflows): ncc and bump to v0.0.6
downgrading gh actions per https://github.com/explore to resolve

```
Error: github.GitHub is not a constructor
```